name: Github Actions
run-name: ${{ github.actor }}
on: [push]
jobs:

  Shift:
      runs-on: ubuntu-latest
      permissions:
        contents: write
        pull-requests: write
      
      steps:
            - name: Checkout code
              uses: actions/checkout@v3
      
            - name: Install nodejs
                    uses: actions/setup-node@v4
                    with:
                      node-version: 20.11.0
                      registry-url: https://registry.npmjs.org
            
            - name: Install dependencies
              run: npm install
      
            - name: Build project
              run: npm run build
      
            - name: Publish to npm
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
